name: Build Mac App

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
   build:
     runs-on: macos-latest
    
     steps:
     - uses: actions/checkout@v2
    
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.9'
    
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pyinstaller
         pip install -r requirements.txt
    
     - name: Build Mac App
       run: |
         # List directories to debug
         ls -la
         # Check if the spec file exists in the root directory
         ls -la *.spec || echo "No spec files in root directory"
         # Check if frame-tools directory exists and list its contents
         if [ -d "frame-tools" ]; then
           ls -la frame-tools/
           ls -la frame-tools/*.spec || echo "No spec files in frame-tools directory"
         else
           echo "frame-tools directory does not exist"
         fi
         # Try to find the spec file anywhere in the repository
         find . -name "*.spec"
         # Use the correct path to the spec file based on the find results
         pyinstaller FrameGifTool.spec
         cd dist
         zip -r FrameGifTool-Mac.zip FrameGifTool.app
    
     - name: Upload Release Asset
       uses: actions/upload-release-asset@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ github.event.release.upload_url }}
         asset_path: ./dist/FrameGifTool-Mac.zip
         asset_name: FrameGifTool-Mac.zip
         asset_content_type: application/zip
