name: Build Mac App

on:
  pull_request:
    branches:
      - main
    types: [closed]
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
   build:
     runs-on: macos-latest
    
     steps:

     - uses: actions/checkout@v3
       with:
         fetch-depth: 0  # Fetch all history for tags
    
     - name: Set up Python

       uses: actions/setup-python@v4
       with:
         python-version: '3.9'
    
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pyinstaller
         pip install -r requirements.txt
    
     - name: Build Mac App
       run: |
         # Find the spec file
         find . -name "*.spec"
         # Use the correct path to the spec file
         pyinstaller FrameGifTool.spec
         cd dist
         zip -r FrameGifTool-Mac.zip FrameGifTool.app
         echo "ZIP_PATH=$(pwd)/FrameGifTool-Mac.zip" >> $GITHUB_ENV
         cd ..
     
     - name: Upload to Release (on push to main)
       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
       run: |
         # Upload the asset to the release
         gh release upload ${{ env.NEW_TAG }} ${{ env.ZIP_PATH }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
     - name: Upload to Release (on release created)
       if: github.event_name == 'release'
       run: |
         # Upload the asset to the release
         gh release upload ${{ github.event.release.tag_name }} ${{ env.ZIP_PATH }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
