name: Build Mac App

on:
  pull_request:
    branches:
      - main
    types: [closed]
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
   build:
     runs-on: macos-latest
    
     steps:

     - uses: actions/checkout@v3
       with:
         fetch-depth: 0  # Fetch all history for tags
    
     - name: Set up Python

       uses: actions/setup-python@v4
       with:
         python-version: '3.9'
    
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
    
     - name: Check for required files
       run: |
         if [ ! -f "logo.png" ]; then
           echo "Warning: logo.png not found in the current directory."
           echo "The application will be built without a custom icon."
         fi
        
         if [ ! -f "frame.png" ]; then
           echo "Warning: frame.png not found in the current directory."
           echo "The application will need a frame image to be selected manually."
         fi
    
     - name: Build Mac App
       run: |
         python3 build_app.py
         cd dist
         zip -r GIF-Framing-Tool-Mac.zip "GIF Framing Tool.app"
         echo "ZIP_PATH=$(pwd)/GIF-Framing-Tool-Mac.zip" >> $GITHUB_ENV
         cd ..
     
     - name: Upload to Release (on push to main)
       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
       run: |
         # Upload the asset to the release
         gh release upload ${{ env.NEW_TAG }} ${{ env.ZIP_PATH }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
     - name: Upload to Release (on release created)
       if: github.event_name == 'release'
       run: |
         # Upload the asset to the release
         gh release upload ${{ github.event.release.tag_name }} ${{ env.ZIP_PATH }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
     - name: Upload Artifact
       uses: actions/upload-artifact@v3
       with:
         name: GIF-Framing-Tool-Mac
         path: ${{ env.ZIP_PATH }}
