name: Build Mac App

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
   build:
     runs-on: macos-latest
    
     steps:
     - uses: actions/checkout@v2
    
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.9'
    
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pyinstaller
         pip install -r requirements.txt
    
     - name: Build Mac App
       run: |
         chmod +x ./makeBuild.sh
         ./makeBuild.sh
    
     - name: Upload Release Asset
       uses: actions/upload-release-asset@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ github.event.release.upload_url }}
         asset_path: ./dist/FrameGifTool-Mac.zip
         asset_name: FrameGifTool-Mac.zip
         asset_content_type: application/zip